/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.support.standup.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GlobalInformation service. Represents a row in the &quot;SUP_GlobalInformation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.support.standup.model.impl.GlobalInformationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.support.standup.model.impl.GlobalInformationImpl}.
 * </p>
 *
 * @author Daniel Javorszky
 * @see GlobalInformation
 * @see com.liferay.support.standup.model.impl.GlobalInformationImpl
 * @see com.liferay.support.standup.model.impl.GlobalInformationModelImpl
 * @generated
 */
public interface GlobalInformationModel extends BaseModel<GlobalInformation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a global information model instance should use the {@link GlobalInformation} interface instead.
	 */

	/**
	 * Returns the primary key of this global information.
	 *
	 * @return the primary key of this global information
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this global information.
	 *
	 * @param primaryKey the primary key of this global information
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the global information ID of this global information.
	 *
	 * @return the global information ID of this global information
	 */
	public long getGlobalInformationId();

	/**
	 * Sets the global information ID of this global information.
	 *
	 * @param globalInformationId the global information ID of this global information
	 */
	public void setGlobalInformationId(long globalInformationId);

	/**
	 * Returns the company ID of this global information.
	 *
	 * @return the company ID of this global information
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this global information.
	 *
	 * @param companyId the company ID of this global information
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this global information.
	 *
	 * @return the group ID of this global information
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this global information.
	 *
	 * @param groupId the group ID of this global information
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this global information.
	 *
	 * @return the user ID of this global information
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this global information.
	 *
	 * @param userId the user ID of this global information
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this global information.
	 *
	 * @return the user uuid of this global information
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this global information.
	 *
	 * @param userUuid the user uuid of this global information
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the date of this global information.
	 *
	 * @return the date of this global information
	 */
	public Date getDate();

	/**
	 * Sets the date of this global information.
	 *
	 * @param date the date of this global information
	 */
	public void setDate(Date date);

	/**
	 * Returns the message of this global information.
	 *
	 * @return the message of this global information
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this global information.
	 *
	 * @param message the message of this global information
	 */
	public void setMessage(String message);

	/**
	 * Returns the display of this global information.
	 *
	 * @return the display of this global information
	 */
	public int getDisplay();

	/**
	 * Sets the display of this global information.
	 *
	 * @param display the display of this global information
	 */
	public void setDisplay(int display);

	/**
	 * Returns the status of this global information.
	 *
	 * @return the status of this global information
	 */
	public int getStatus();

	/**
	 * Sets the status of this global information.
	 *
	 * @param status the status of this global information
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GlobalInformation globalInformation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GlobalInformation> toCacheModel();

	@Override
	public GlobalInformation toEscapedModel();

	@Override
	public GlobalInformation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}